# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongoid_touch"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Grabo"]
  s.date = "2012-03-21"
  s.description = "A tiny mongoid extension to provide the `touch` method known from ActiveRecord to Mongoid::Document."
  s.email = "chris@dinarrr.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/config/locales/en.yml",
    "lib/mongoid/document/touch.rb",
    "lib/mongoid/errors/document_not_updated.rb",
    "lib/mongoid/errors/frozen_instance.rb",
    "lib/mongoid/errors/missing_field.rb",
    "lib/mongoid_touch.rb",
    "mongoid_touch.gemspec",
    "spec/mongoid_touch_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/asaaki/mongoid_touch"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Mongoid::Document with a touch method"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ["~> 2.4.6"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<bson_ext>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.9.0"])
      s.add_development_dependency(%q<mongoid-rspec>, ["~> 1.4.4"])
      s.add_development_dependency(%q<database_cleaner>, ["~> 0.7.1"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, ["~> 2.4.6"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.9.0"])
      s.add_dependency(%q<mongoid-rspec>, ["~> 1.4.4"])
      s.add_dependency(%q<database_cleaner>, ["~> 0.7.1"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, ["~> 2.4.6"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.9.0"])
    s.add_dependency(%q<mongoid-rspec>, ["~> 1.4.4"])
    s.add_dependency(%q<database_cleaner>, ["~> 0.7.1"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

